/**
 * Webhook contract replay harness (generated by the webhook-contract plugin).
 *
 * Replays the synthetic deliveries in fixtures/ against your handler (see
 * replay_hooks.mjs) and asserts the delivery contract:
 *
 *   - every delivery is answered with a status the provider accepts
 *     (an unhandled rejection counts as a 500, which is what the provider sees),
 *   - side effects stay within their per-scenario bounds: at least
 *     `effect_min` and at most `effect_budget` calls, measured through the
 *     probe you wired to the real write paths,
 *   - for order scenarios, the FINAL STATE after the violated arrival order
 *     equals the final state after the natural order (order-equivalence).
 *     A snapshot that serializes to nothing on both runs fails the scenario
 *     instead of letting the comparison pass vacuously.
 *
 * Run:  node --test test_replay.mjs
 *
 * handle() may be sync or async, and the probe methods may be sync or async -
 * the harness awaits their results either way. The retry scenario's first
 * delivery is an ordinary call - the harness discards its response to
 * simulate the lost response, so handle() needs no special casing (a handler
 * cannot tell a retry after a lost response from a duplicate, and must not
 * need to).
 *
 * This file is generated; edit replay_hooks.mjs, not this file.
 */

import assert from "node:assert/strict";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

import { PROBE, handle } from "./replay_hooks.mjs";

const FIXTURES_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), "fixtures");

// Rejections/throws per delivery, so failures can show WHY a delivery
// answered 500 instead of just that it did.
const crashLog = [];

// Serialized snapshots that carry no state. If BOTH order-scenario snapshots
// look like this, there is nothing to compare and the scenario fails instead
// of passing vacuously.
const EMPTY_STATES = new Set(["{}", "[]", "null", '""', "0", "false"]);

// Private marker for "the provider never saw a response" - the first attempt
// of retry_after_failure, whose outcome the harness discards. A Symbol cannot
// be produced by a handler's return value; undefined or null is a bug and
// fails the status assertion.
const LOST = Symbol("lost-response");

function walk(dir) {
  const out = [];
  if (!existsSync(dir)) return out;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.name.endsWith(".json")) out.push(full);
  }
  return out.sort();
}

function sortDeep(value) {
  // Map, Set and Promise serialize as "{}" and would make the order check
  // compare two empty objects; fail loudly instead of silently.
  if (value instanceof Map || value instanceof Set || value instanceof Promise || typeof value === "function") {
    throw new TypeError(
      `${value?.constructor?.name ?? typeof value} is not JSON-serializable; return plain JSON state`
    );
  }
  if (Array.isArray(value)) return value.map(sortDeep);
  if (value !== null && typeof value === "object") {
    const out = {};
    for (const key of Object.keys(value).sort()) out[key] = sortDeep(value[key]);
    return out;
  }
  return value;
}

/** Order-independent JSON rendering (sorted keys, recursively). */
const stable = (value) => JSON.stringify(sortDeep(value));

function naturalOrder(deliveries) {
  return [...deliveries].sort(
    (a, b) =>
      String(a.order_key ?? "").localeCompare(String(b.order_key ?? "")) ||
      (a.order_seq ?? a.seq ?? 0) - (b.order_seq ?? b.seq ?? 0)
  );
}

async function runDelivery(delivery) {
  const raw = delivery.raw_body ?? JSON.stringify(delivery.body);
  const headers = delivery.headers ?? {};
  try {
    const result = await handle(raw, headers);
    return delivery.fail_attempt ? LOST : result;
  } catch (err) {
    crashLog.push(`delivery ${delivery.seq}: ${err && err.stack ? err.stack : err}`);
    // On the flagged first attempt the response is discarded - the lost
    // response that makes the provider retry; effects may have landed and
    // the retry (the next delivery) must not repeat them.
    return delivery.fail_attempt ? LOST : 500;
  }
}

/** Reset the probe, replay every delivery in list order, return status codes. */
async function runAll(deliveries) {
  crashLog.length = 0;
  await PROBE.reset();
  const statuses = [];
  for (const delivery of deliveries) statuses.push(await runDelivery(delivery));
  return statuses;
}

const fixtureFiles = walk(FIXTURES_DIR);

test("fixtures exist", () => {
  assert.ok(fixtureFiles.length > 0, "no fixtures found; generate them from the contract first");
});

for (const file of fixtureFiles) {
  const rel = path.relative(FIXTURES_DIR, file);
  test(`contract: ${rel}`, async () => {
    const fixture = JSON.parse(readFileSync(file, "utf8"));
    const scenario = fixture.scenario ?? "?";
    const expectations = fixture.expectations ?? {};
    const deliveries = fixture.deliveries ?? [];

    const statuses = await runAll(deliveries);
    const expected = expectations.statuses ?? [200];
    for (const [index, status] of statuses.entries()) {
      if (status === LOST) continue; // discarded first attempt; nothing to assert
      // Name the delivery by its fixture seq, like the crash log does - an
      // index would not match the fixture document.
      const seq = deliveries[index]?.seq ?? index;
      let message = `${scenario}: delivery ${seq} answered ${status} but the contract allows ${JSON.stringify(expected)}`;
      if (status === 500 && crashLog.length > 0) message += ` | handler raised: ${crashLog.join(" ; ")}`;
      assert.ok(expected.includes(status), message);
    }

    const counts = await PROBE.counts();
    for (const [effect, floor] of Object.entries(expectations.effect_min ?? {})) {
      const actual = counts[effect] ?? 0;
      assert.ok(
        actual >= floor,
        `${scenario}: side effect '${effect}' fired only ${actual} time(s); the handler must apply it at ` +
          `least ${floor} time(s) for these deliveries (a handler that drops events passes upper bounds only)`
      );
    }
    for (const [effect, budget] of Object.entries(expectations.effect_budget ?? {})) {
      const actual = counts[effect] ?? 0;
      assert.ok(actual <= budget, `${scenario}: side effect '${effect}' fired ${actual} time(s), budget is ${budget}`);
    }

    const reference = expectations.reference;
    if (reference && reference.order === "natural") {
      // Serialise BEFORE the second run: if snapshot() returns a live
      // reference, reset() would otherwise rewrite it under us and both sides
      // would compare equal forever.
      let violatingSnapshot;
      try {
        violatingSnapshot = stable(await PROBE.snapshot());
      } catch (err) {
        assert.fail(`PROBE.snapshot() must be JSON-serializable: ${err}`);
      }
      await runAll(naturalOrder(deliveries));
      let naturalSnapshot;
      try {
        naturalSnapshot = stable(await PROBE.snapshot());
      } catch (err) {
        assert.fail(`PROBE.snapshot() must be JSON-serializable: ${err}`);
      }
      if (EMPTY_STATES.has(violatingSnapshot) && EMPTY_STATES.has(naturalSnapshot)) {
        assert.fail(
          `${scenario}: PROBE.snapshot() returned ${violatingSnapshot} for both runs; there is no state ` +
            `to compare and the order check would pass vacuously. Make snapshot() return the ` +
            `state your handler writes (plain JSON-serializable data).`
        );
      }
      assert.equal(
        violatingSnapshot,
        naturalSnapshot,
        `${scenario}: final state after the violated arrival order differs from the natural-order final state.\n` +
          `violated: ${violatingSnapshot}\nnatural:  ${naturalSnapshot}`
      );
    }
  });
}
