"""Webhook contract replay harness (generated by the webhook-contract plugin).

Replays the synthetic deliveries in fixtures/ against your handler (see
replay_hooks.py) and asserts the delivery contract:

  * every delivery is answered with a status the provider accepts
    (an unhandled crash counts as a 500, which is what the provider sees),
  * side effects stay within their per-scenario bounds: at least
    `effect_min` and at most `effect_budget` calls, measured through the
    probe you wired to the real write paths,
  * for order scenarios, the FINAL STATE after the violated arrival order
    equals the final state after the natural order (order-equivalence).
    A snapshot that serializes to nothing on both runs fails the scenario
    instead of letting the comparison pass vacuously.

Run:  python test_replay.py          (unittest; pytest works too)

`handle()` may be a plain function or an `async def`, and the probe methods
may be sync or async; awaitables run on a fresh event loop per call. The
retry scenario's first delivery is an ordinary call - the harness discards
its response to simulate the lost response, so `handle()` needs no special
casing (a handler cannot tell a retry after a lost response from a duplicate,
and must not need to).

This file is generated; edit replay_hooks.py, not this file.
"""

import asyncio
import inspect
import json
import unittest
from pathlib import Path

from replay_hooks import PROBE, handle

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"

# (delivery seq, repr) for every unhandled handler exception, so failures can
# show WHY a delivery answered 500 instead of just that it did.
CRASH_LOG = []

# Serialized snapshots that carry no state. If BOTH order-scenario snapshots
# look like this, there is nothing to compare and the scenario fails instead
# of passing vacuously.
EMPTY_STATES = ("{}", "[]", "null", '""', "0", "false")

# Private marker for "the provider never saw a response" - the first attempt
# of retry_after_failure, whose outcome the harness discards. A handler cannot
# return this value by accident; returning None is a bug and fails the status
# assertion.
LOST = object()


def resolve(value):
    """Handler and probe results may be plain values or awaitables."""
    if inspect.isawaitable(value):
        return asyncio.run(value)
    return value


def load_fixture_paths():
    if not FIXTURES_DIR.exists():
        return []
    return sorted(FIXTURES_DIR.rglob("*.json"))


def run_delivery(delivery):
    """Replay one delivery. Returns its status, or LOST when the response is
    discarded: on the flagged first attempt of retry_after_failure the
    provider never saw the answer - that lost response is why it retries."""
    raw = delivery.get("raw_body")
    if raw is None:
        raw = json.dumps(delivery["body"], sort_keys=True)
    headers = delivery.get("headers") or {}
    try:
        result = resolve(handle(raw, headers))
    except Exception as exc:
        CRASH_LOG.append((delivery.get("seq"), repr(exc)))
        if delivery.get("fail_attempt"):
            return LOST  # effects may have landed before the crash; the retry must not repeat them
        return 500
    return LOST if delivery.get("fail_attempt") else result


def run_all(deliveries):
    """Reset the probe, replay every delivery in list order, return status codes."""
    del CRASH_LOG[:]
    resolve(PROBE.reset())
    return [run_delivery(delivery) for delivery in deliveries]


def natural_order(deliveries):
    return sorted(deliveries, key=lambda d: (str(d.get("order_key", "")), d.get("order_seq", d.get("seq", 0))))


def stable(value):
    """Order-independent JSON rendering (sorted keys, recursively)."""
    return json.dumps(value, sort_keys=True)


class ContractReplay(unittest.TestCase):
    def test_delivery_contract(self):
        fixture_paths = load_fixture_paths()
        self.assertTrue(fixture_paths, "no fixtures found; generate them from the contract first")
        for path in fixture_paths:
            with self.subTest(fixture=str(path.relative_to(FIXTURES_DIR))):
                fixture = json.loads(path.read_text(encoding="utf-8"))
                scenario = fixture.get("scenario", "?")
                expectations = fixture.get("expectations") or {}

                deliveries = fixture.get("deliveries") or []
                statuses = run_all(deliveries)
                expected_statuses = expectations.get("statuses") or [200]
                for index, status in enumerate(statuses):
                    if status is LOST:
                        continue  # discarded first attempt; nothing to assert
                    # Name the delivery by its fixture seq, like the crash log
                    # does - an index would not match the fixture document.
                    seq = (deliveries[index] or {}).get("seq", index)
                    message = "{}: delivery {} answered {} but the contract allows {}".format(
                        scenario, seq, status, expected_statuses
                    )
                    if status == 500 and CRASH_LOG:
                        message += " | handler raised: " + " ; ".join(
                            repr_exc for _, repr_exc in CRASH_LOG
                        )
                    self.assertIn(status, expected_statuses, message)

                counts = resolve(PROBE.counts())
                for effect, floor in (expectations.get("effect_min") or {}).items():
                    actual = counts.get(effect, 0)
                    self.assertGreaterEqual(
                        actual,
                        floor,
                        "{}: side effect '{}' fired only {} time(s); the handler must apply it at "
                        "least {} time(s) for these deliveries (a handler that drops events passes "
                        "upper bounds only)".format(scenario, effect, actual, floor),
                    )
                for effect, budget in (expectations.get("effect_budget") or {}).items():
                    actual = counts.get(effect, 0)
                    self.assertLessEqual(
                        actual,
                        budget,
                        "{}: side effect '{}' fired {} time(s), budget is {}".format(scenario, effect, actual, budget),
                    )

                reference = expectations.get("reference")
                if isinstance(reference, dict) and reference.get("order") == "natural":
                    # Serialise BEFORE the second run: if snapshot() returns a live
                    # reference, reset() would otherwise rewrite it under us and
                    # both sides would compare equal forever.
                    try:
                        violating_snapshot = stable(resolve(PROBE.snapshot()))
                    except TypeError as exc:
                        self.fail("PROBE.snapshot() must be JSON-serializable: {}".format(exc))
                    run_all(natural_order(deliveries))
                    try:
                        natural_snapshot = stable(resolve(PROBE.snapshot()))
                    except TypeError as exc:
                        self.fail("PROBE.snapshot() must be JSON-serializable: {}".format(exc))
                    if violating_snapshot in EMPTY_STATES and natural_snapshot in EMPTY_STATES:
                        self.fail(
                            "{}: PROBE.snapshot() returned {} for both runs; there is no state "
                            "to compare and the order check would pass vacuously. Make snapshot() "
                            "return the state your handler writes (plain JSON-serializable data).".format(
                                scenario, violating_snapshot
                            )
                        )
                    self.assertEqual(
                        violating_snapshot,
                        natural_snapshot,
                        "{}: final state after the violated arrival order differs from the "
                        "natural-order final state.\nviolated: {}\nnatural:  {}".format(
                            scenario, violating_snapshot, natural_snapshot
                        ),
                    )


if __name__ == "__main__":
    unittest.main(verbosity=2)
